# Usage and documentation can be found on: https://realm.github.io/SwiftLint/
disabled_rules:
  - control_statement
  - unused_optional_binding
  - nesting
  - blanket_disable_command
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count

analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self

included:
  - Packages
  - ModularSampleApp
  - ModularSampleAppTests
  - ModularSampleAppUITests
excluded:
  - Build
  - "*.generated.swift"

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: 
  severity: warning

force_try:
  severity: warning

line_length: 
  warning: 150

type_body_length:
  warning: 300
  error: 400

vertical_whitespace:
  max_empty_lines: 
    warning: 1

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded: iPhone 
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length:
    error: 3
  excluded:
    - ui
    - id
    - URL
    - ok
    - x
    - y
    - i
    - j
  allowed_symbols: ["_"] # these are allowed in type names

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)