name: Tests
on: [push, workflow_dispatch]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@V3
      - name: Github action for SwiftLint
        uses: norio-nomura/action-swiftlin@3.2.1